Changed check remote repo version v6

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,7 +21,7 @@ jobs:
       run: |
         cd remote-repo
         git fetch --tags
-        LATEST_VERSION=$(git describe --tags --abbrev=0 --always) || echo "Failed to get the latest version"
+        LATEST_VERSION=$(git tag | sort -V -r | head -n 1) || echo "Failed to get the latest version"
         echo "Latest version: $LATEST_VERSION"
         if [ -n "$LATEST_VERSION" ]; then
           echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
