Changed check remote repo version v2

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,5 +20,11 @@ jobs:
       id: latest_version
       run: |
         cd remote-repo
-        LATEST_VERSION=$(git describe --tags --abbrev=0)
-        echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
+        git fetch --tags
+        LATEST_VERSION=$(git describe --tags --abbrev=0) || echo "Failed to get the latest version"
+        if [ -n "$LATEST_VERSION" ]; then
+          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
+        else
+          echo "Could not determine the latest version"
+          exit 1
+        fi
